services:
  redis:
    container_name: "gin-test-redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  mysql:
    container_name: "gin-test-mysql"
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"