info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: get ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show an ping
      tags:
      - ping
swagger: "2.0"
