info:
  contact: {}
paths:
  /list-buckets:
    get:
      description: S3 Bucket의 리스트를 가져옵니다.
      produces:
      - text/plain
      responses:
        "200":
          description: bucket names
          schema:
            type: string
      summary: List S3 buckets
      tags:
      - aws
  /ping:
    get:
      consumes:
      - application/json
      description: get ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show an ping
      tags:
      - ping
  /user/{key}:
    get:
      description: DynamoDB 내 테이블에서 키를 이용하여 값을 가져옵니다.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: DynamoDB 내 테이블에서 키를 이용하여 값을 가져옵니다.
      tags:
      - aws
swagger: "2.0"
